# This is a basic workflow to help you get started with Actions
 
name: CI
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    # The type of runner that the job will run on
    # needs: bash-script
    runs-on: self-hosted
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands for windows 
      - name: Checkout code
        uses: actions/checkout@v2
        - name: Execute Tosca Client
        run: |
         .\tosca_execution_client.ps1 -toscaServerUrl " https://dextosca01.dexcom.dexcominc.com" -projectName "Tosca_dev" -events '["Stelo_Smoke"]' -clientId "wtWxQisS9UqTRNmgr6mw7g" -clientSecret "T-J2H9BOM0-QPZ1SHcoHcQfNqBWPeMCESrqPNICIU1fg"
        # shell: pwsh
